# Numpy
Numpy is a fundamental Library for scientific computing in python. It provides support for arrays and matrices , along with a collection of mathematical functions to operate on these data structures. It this lesson , we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

## Create array using numpy

## Create a 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1 d array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## Convert 2-d aaray 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy of array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of demensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of demensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [14]:
## Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element Wise adddition 
print("addition:",arr1 + arr2)

##element Wise subtraction 
print("Subtraction:",arr1 - arr2)

##element Wise Multiplication
print("Multiplication:",arr1 * arr2)

##element Wise Division
print("Division:",arr1 / arr2)



addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal Function 
arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponetial
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)


Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [33]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [28]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [40]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:] =100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [42]:
## Statistical concepts--Normalization

## to have mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data 
normalized_data = (data-mean) / std_dev
print("Normalized Data:" , normalized_data)


Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [43]:
## Statistical concepts -- mean , median , standard deviation and Variance

data = np.array([1,2,3,4,5,6,7,8,9,10])


# Mean
mean = np.mean(data)
print("Mean:",mean)

# Median 
median = np.median(data)
print("Median:",median)

## Standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

## Variance
variance = np.var(data)
print("Variance:",variance)




Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [47]:
## Logical operation

data =np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >=5 ) & (data < 8)]

array([5, 6, 7])