# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [6]:
## Assignment 1 
## Question 1 : Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np

arr = np.random.randint(1,21 , size=(5,5))
print("Original Array:")
print(arr)

arr[:,2]=1
print("New Array:")
print(arr)



Original Array:
[[ 8  2 12  9 19]
 [ 1  1  9 14  9]
 [14 19 15 12 13]
 [ 6 18  5 15 16]
 [ 8  8 12  1  3]]
New Array:
[[ 8  2  1  9 19]
 [ 1  1  1 14  9]
 [14 19  1 12 13]
 [ 6 18  1 15 16]
 [ 8  8  1  1  3]]


In [4]:
## Question 2 : Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
import numpy as np

array = np.arange(1,17).reshape((4,4))
print("Original Array :")
print(array)

np.fill_diagonal(array,0)
print("New Array:")
print(array)



Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
New Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
## Assignment 2 : 
# Questionn 1 : Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

import numpy as np 
arr = np.arange(1,37).reshape(6,6)
print("Original Array :")
print(arr)

sub_arr = arr[2:5,1:4]
print("New Array : ")
print(sub_arr)

Original Array :
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
New Array : 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [21]:
## Question 2 : Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

import numpy as np 

arr1 = np.random.randint(1,21,size=(5,5))
print("Array :")
print(arr1)

border_elements = np.concatenate((arr1[0, :], arr1[-1, :], arr1[1:-1, 0], arr1[1:-1, -1]))
print("Border elements:")
print(border_elements)

Array :
[[11 13  2 11  2]
 [20  5 17 16 20]
 [ 4 19  1 14 16]
 [11 10 17 16 13]
 [18  3 12 17  3]]
Border elements:
[11 13  2 11  2 18  3 12 17  3 20  4 11 20 16 13]


In [22]:
## Assignment 3 :
## Question 1 : Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

import numpy as np 

array1 = np.random.randint(1,11,size=(3,4))
print("First Array:")
print(array1)

array2 = np.random.randint(1,11,size=(3,4))
print("Second Array :")
print(array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addtion :")
print(addition)

print("Subtraction :")
print(subtraction)

print("Multiplication")
print(multiplication)

print("Division")
print(division)

First Array:
[[ 2  3  8  4]
 [ 6 10  3  4]
 [ 2  1  8  8]]
Second Array :
[[ 6 10  6  1]
 [ 4  5 10  2]
 [ 9  8  3  3]]
Addtion :
[[ 8 13 14  5]
 [10 15 13  6]
 [11  9 11 11]]
Subtraction :
[[-4 -7  2  3]
 [ 2  5 -7  2]
 [-7 -7  5  5]]
Multiplication
[[12 30 48  4]
 [24 50 30  8]
 [18  8 24 24]]
Division
[[0.33333333 0.3        1.33333333 4.        ]
 [1.5        2.         0.3        2.        ]
 [0.22222222 0.125      2.66666667 2.66666667]]


In [24]:
## Question 2 : Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

import numpy as np

Array = np.arange(1,17).reshape(4,4)
print("Array : ")
print(Array)

row_sum = np.sum(Array,axis=1)
col_sum = np.sum(Array,axis=0)

print("Row Sum :")
print(row_sum)
print("Column Sum :")
print(col_sum)

Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row Sum :
[10 26 42 58]
Column Sum :
[28 32 36 40]


In [26]:
## Assignment 4 : 
## Question 1 : Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

import numpy as np

arr0 =np.random.randint(1,21,size=(5,5))
print("Array :")
print(arr)

mean = np.mean(arr0)
median = np.median(arr0)
std = np.std(arr0)
var = np.var(arr0)

print("Mean of array :",mean)
print("Median of array :",median)
print("Standard deviation of array :",std)
print("Variance of array :",var)


Array :
[[ 7  5 19  4 12]
 [17  3 15  7 15]
 [ 4  5  3 13 18]
 [ 3  7 11  1 11]
 [ 4  7 17  1  8]]
Mean of array : 9.84
Median of array : 9.0
Standard deviation of array : 6.576807736280574
Variance of array : 43.254400000000004


In [28]:
## Question 2 : Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

import numpy as np 

Array1 = np.arange(1,10).reshape((3,3))
print("Array :")
print(Array1)

mean = np.mean(Array1)
std_dev = np.std(Array1)
Normalization = (Array1 - mean ) / std_dev

print("Normalization:")
print(Normalization)

Array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalization:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [30]:
## Assignment 5 : 
## Question 1 : Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

import numpy as np
Arr9 = np.random.randint(1,11,size=(3,3))
row_Arr = np.random.randint(1,11,size=(3,))
print("Original Array :")
print(Arr9)
print("1-D Array :")
print(row_Arr)

result = Arr9 + row_Arr

print("Final Array :")
print(result)




Original Array :
[[ 4  2  5]
 [ 8 10  8]
 [ 3  7  5]]
1-D Array :
[ 7 10  1]
Final Array :
[[11 12  6]
 [15 20  9]
 [10 17  6]]


In [33]:
## Question 2 : Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

import numpy as np
Arr9 = np.random.randint(1,11,size=(4,4))
col_Arr = np.random.randint(1,11,size=(4,))
print("Original Array :")
print(Arr9)
print("1-D Array :")
print(col_Arr)

result = Arr9 - col_Arr[:, np.newaxis]

print("Final Array :")
print(result)

Original Array :
[[ 7  3  5  7]
 [10  4  3  9]
 [ 6  1 10 10]
 [ 3  9  3  3]]
1-D Array :
[2 7 1 8]
Final Array :
[[ 5  1  3  5]
 [ 3 -3 -4  2]
 [ 5  0  9  9]
 [-5  1 -5 -5]]
